### ISSUE TITLE
Cell type annotations Fig.1B in seurat object not found!

### ISSUE THREAD

**Issue by LazDaria** [JinmiaoChenLab/Bone_Marrow_Aging#1]
Hi, 

thank you for this great work! This atlas will be useful to many of us working in bone marrow research. I downloaded the Seurat object from DISCO, however I can't find the slot with the cell type annotations visualized in Figure 1B. which slot entails these annotations? 
I checked the following, but obtained different annotations: 
@active.ident
@meta.data$ct
@meta.data$predicted_cell_type

Thanks in advance!

**Comment by lmw123** [comment]
Hi,
Thanks for your interest in our bone marrow atlas. We put the cell type information as "ct" in metadata. 

Please let me know if you have any other questions. Thanks

**Comment by LazDaria** [comment]
Hi and thanks for your prompt reply!
ct in metadata gives me the following celltypes:
![Bildschirmfoto 2023-07-13 um 12 30 27](https://github.com/JinmiaoChenLab/Bone_Marrow_Aging/assets/44135481/80332266-b060-45b2-b183-1fbb337d5d11)
However, I cannot find all celltypes there, e.g. promeylocyte, S100A+ preNeutrophil etc.). Is there a finer annotation saved somewhere in the seurat object?

**Comment by lmw123** [comment]
Hi,

I think you may have downloaded data of bone marrow atlas v1. Could you download atlas 2.0 via this link https://zenodo.org/record/7615517/files/disco_bone_marrow_v2.0.rds?download=1 

Thanks

**Comment by LazDaria** [comment]
Thank you! The [link](http://www.immunesinglecell.org/download) on DISCO seems to be the old one. I now found all celltypes in version 2.0. The "data" slot in assay "RNA" is empty. Is the integrated data saved in counts?

**Comment by lmw123** [comment]
Yes, We didn't include integrated in this file as it is too large. However, the pca within this object was got from batch corrected value. For most analyses, you can utilize the raw normalized data. Please ensure that you normalize the data prior to usage.

rna.data = NormalizeData(rna.data)

Thanks

**Comment by LazDaria** [comment]
Thank you for the information and the fast answers!
